spring:
  application:
    name: task-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mongodb:
    uri: mongodb://localhost:27017/taskdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    root: INFO
    io.zipkin: DEBUG
    io.micrometer.tracing: DEBUG
  com:
      example: DEBUG
feign:
  circuitbreaker:
    enabled: true
resilience4j:
  circuitbreaker:
    instances:
      studentService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

server:
  port: 8083
